services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/app/Dockerfile
    container_name: bank_management_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/dev/app/php.ini:/usr/local/etc/php/php.ini
    networks:
      - bank_management_network

  nginx:
    image: nginx:alpine
    container_name: bank_management_nginx
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/dev/nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - bank_management_network

  db:
    image: mysql:8.0
    container_name: bank_management_db
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: laravel
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - bank_management_network

networks:
  bank_management_network:

volumes:
  dbdata:
